version: "3"
services:
  database.postgres:
    image: sameersbn/postgresql:latest
    container_name: postgres
    environment:
      - PG_PASSWORD=adminadmin # 修改数据库密码
      - DB_EXTENSION=pg_trgm
    volumes:
      - /volume1/docker/ttrss/data/:/var/lib/postgresql/ # 特别注意，套件在哪个volume就填几，volume2是需要修改的值
    restart: always
 
  service.rss:
    image: wangqiru/ttrss:latest
    container_name: ttrss
    ports:
      - 5005:80
    environment:
      - SELF_URL_PATH=http://127.0.0.1:5005/ # 下面7个参数后期可在docker中修改，所以暂时不需要改动
      - DB_HOST=database.postgres
      - DB_PORT=5432 # 数据库端口，别动它
      - DB_NAME=ttrss
      - DB_USER=postgres
      - DB_PASS=adminadmin # 上面的密码
      - ENABLE_PLUGINS=auth_internal,fever # 默认开启
    stdin_open: true
    tty: true
    restart: always
    command: sh -c 'sh /wait-for.sh database.postgres:5432 -- php /configure-db.php && exec s6-svscan /etc/s6/' # 别随便改动，这是容器启动时执行的命令
